.TH cdbdump 1
.SH NAME
cdbdump \- print the contents of a constant database
.SH SYNOPSIS
.B cdbdump
.SH DESCRIPTION
.B cbddump
reads a constant database from its standard input
and prints its contents, in
.B cbdmake
format,
on standard output.
.SH "SEE ALSO"
cdbget(1),
cdbmake(1),
cdb_firstkey(3),
cdb_nextkey(3)
