// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* tsa.h
   Generated by wsdl2h 1.2.6c from tsa.wsdl and typemap.dat
   2006-08-08 16:04:01 GMT
   Copyright (C) 2001-2005 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control schema namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

*/

/******************************************************************************\
 *                                                                            *
 * tsa                                                                        *
 *                                                                            *
\******************************************************************************/

//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/

// This service uses SOAP 1.2 namespaces:
//gsoap SOAP-ENV schema namespace:	http://www.w3.org/2003/05/soap-envelope
//gsoap SOAP-ENC schema namespace:	http://www.w3.org/2003/05/soap-encoding

/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns = "tsa"

*/

//gsoap ns    schema namespace:	tsa
//gsoap ns    schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/


/// Built-in type "xs:base64Binary".
struct xsd__base64Binary
{	unsigned char *__ptr;
	int __size;
	char *id, *type, *option; /* NOTE: for DIME and MTOM XOP attachments only */
};



/// Element "tsa":TSA-REPLY of complexType.

/// "tsa":TSA-REPLY is a complexType.
struct _ns__TSA_REPLY
{
/// Element request of type xs:base64Binary.
    struct xsd__base64Binary             request                        1;	///< Required element.
/// Element token of type xs:string.
    char*                                token                          0;	///< Nullable pointer.
/// Element section of type xs:string.
    char*                                section                        0;	///< Nullable pointer.
/// Element policy of type xs:string.
    char*                                policy                         0;	///< Nullable pointer.
};


/// Element "tsa":TSA-REPLYResponse of complexType.

/// "tsa":TSA-REPLYResponse is a complexType.
struct _ns__TSA_REPLYResponse
{
/// Element response of type xs:base64Binary.
    struct xsd__base64Binary*            response                       0;	///< Nullable pointer.
};

/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns   service name:	TSA 
//gsoap ns   service type:	TSAPortType 
//gsoap ns   service port:	http://10.30.1.131:4433/ 
//gsoap ns   service namespace:	tsa 
//gsoap ns   service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage TSA Definitions

@section TSA_bindings Bindings
  - @ref TSA

*/

/**

@page TSA Binding "TSA"

@section TSA_service Service Documentation "TSA"
gSOAP 2.7.6c generated service definition

@section TSA_operations Operations of Binding  "TSA"
  - @ref __ns__TSA_REPLY

@section TSA_ports Endpoints of Binding  "TSA"
  - http://10.30.1.131:4433/

*/

/******************************************************************************\
 *                                                                            *
 * TSA                                                                        *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * __ns__TSA_REPLY                                                            *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns__TSA_REPLY" of service binding "TSA"

/**

Operation details:

Service definition of function ns__TSA_REPLY
  - SOAP document/literal style

C stub function (defined in soapClient.c[pp]):
@code
  int soap_call___ns__TSA_REPLY(struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    struct _ns__TSA_REPLY*              ns__TSA_REPLY,
    // response parameters:
    struct _ns__TSA_REPLYResponse*      ns__TSA_REPLYResponse
  );
@endcode

*/

//gsoap ns   service method-style:	TSA_REPLY document
//gsoap ns   service method-encoding:	TSA_REPLY literal
int __ns__TSA_REPLY(
    struct _ns__TSA_REPLY*              ns__TSA_REPLY,
    struct _ns__TSA_REPLYResponse*      ns__TSA_REPLYResponse ///< response parameter
);

/* End of tsa.h */
